<a href="https://colab.research.google.com/github/basangoudapatil/Task-8/blob/main/KNN_Assignment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [2]:
import pandas as pd

In [3]:
import numpy as np

**Importing the dataset**

In [4]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [37]:
df.shape

(400, 5)

In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [7]:
df =df.drop_duplicates()

**Splitting the dataset into the Training set and Test set**

In [10]:
#As I am using only Age and Estimated Salary to predict the target variable
#Converstion of Gender is not requires

X = df.loc[:,['Age','EstimatedSalary']].values #All the rows and the required columns
y = df.loc[:,'Purchased'].values #All the rows of Purchased column

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=4)

In [16]:
X_train.shape, y_train.shape

((280, 2), (280,))

In [14]:
X_train[0:5]

array([[    28,  44000],
       [    34,  43000],
       [    37,  62000],
       [    35,  91000],
       [    53, 143000]])

In [18]:
y_train[0:5]

array([0, 0, 0, 1, 1])

**Feature Scaling**

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
X_train[0:5]

array([[-0.94662201, -0.78624689],
       [-0.36979032, -0.8156904 ],
       [-0.08137447, -0.2562637 ],
       [-0.2736517 ,  0.59759811],
       [ 1.45684338,  2.12866066]])

**Fitting K-NN to the Training set**

In [25]:
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import cross_val_score

for k in range(1, 11, 1):
  knn = KNeighborsClassifier(k) #initialising model with hyperparameter-k for a range from 0 to 20
  knn.fit(X_train, y_train) #training the model with X_train and y_train
  print('K value: ',k, 'train score: ',knn.score(X_train, y_train), 'score: ', np.mean(cross_val_score(knn, X_train, y_train, cv=10))) #predicting the best value of Hyperparameter so that there is no overfitting or underfitting

K value:  1 train score:  0.9964285714285714 score:  0.8785714285714287
K value:  2 train score:  0.9464285714285714 score:  0.8428571428571429
K value:  3 train score:  0.9428571428571428 score:  0.8821428571428573
K value:  4 train score:  0.9214285714285714 score:  0.8857142857142858
K value:  5 train score:  0.925 score:  0.9
K value:  6 train score:  0.9285714285714286 score:  0.8892857142857142
K value:  7 train score:  0.925 score:  0.9
K value:  8 train score:  0.925 score:  0.9
K value:  9 train score:  0.925 score:  0.9142857142857143
K value:  10 train score:  0.925 score:  0.9035714285714285


In [26]:
#for a valu of k=9, the score is highest, so it is the best value for k hyperparameter
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
k=9
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

**Predicting the Test set results**

In [34]:
y_pred = knn.predict(X_test)
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1.head()

Actual  Predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       0          0

In [35]:
from sklearn.metrics import roc_auc_score, accuracy_score

acc = accuracy_score(y_test, y_pred)
print("Test set accuracy: {:.2f}".format(acc))
acc = roc_auc_score(y_test, y_pred)
print("Test set auc: {:.2f}".format(acc))
Score = knn.score(X_test, y_test)
print('The score of the model: {:.2f}'.format(Score))

Test set accuracy: 0.90
Test set auc: 0.90
The score of the model: 0.90


**Making the Confusion Matrix**

In [36]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred, y_test)

array([[73,  4],
       [ 8, 35]])